<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_General</name>
   <tag></tag>
   <elementGuidId>d31d4e87-90bb-4886-b07f-2fe15a98ee73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c65-16.ng-trigger.ng-trigger-collapseMotion.ant-menu.ant-menu-inline.ant-menu-sub.ng-star-inserted > ul.list-sub.ng-star-inserted > li.ant-menu-item.ng-star-inserted > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6938b8a6-310f-4ee3-8698-3f013edf569c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master-data/general</value>
      <webElementGuid>cd66cca7-391e-4a85-a344-2df83ca3f12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General </value>
      <webElementGuid>7d7f2f77-bc34-4762-84ba-aaa855284200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-open&quot;]/div[@class=&quot;ng-tns-c65-16 ng-trigger ng-trigger-collapseMotion ant-menu ant-menu-inline ant-menu-sub ng-star-inserted&quot;]/ul[@class=&quot;list-sub ng-star-inserted&quot;]/li[@class=&quot;ant-menu-item ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>ab12caa6-2e7e-4516-94be-32ece9f5ac66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49c703c3-3644-4527-928e-21039dec3c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master-data/general</value>
      <webElementGuid>f6fa56bb-3a36-46c2-93ae-1a3d7060a52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General </value>
      <webElementGuid>e2a812c7-a098-4639-9771-2f786b4442e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-open&quot;]/div[@class=&quot;ng-tns-c65-16 ng-trigger ng-trigger-collapseMotion ant-menu ant-menu-inline ant-menu-sub ng-star-inserted&quot;]/ul[@class=&quot;list-sub ng-star-inserted&quot;]/li[@class=&quot;ant-menu-item ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>dc46f7d9-397d-4e04-8ed2-a3c89a9ef1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>569e9d05-d4cd-4275-8e5d-8f44fec14915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master-data/general</value>
      <webElementGuid>38ecac42-fa3a-4323-b94a-2a832ecbfeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General </value>
      <webElementGuid>445c2f6f-ed73-464a-9522-ca46dcffbfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-open&quot;]/div[@class=&quot;ng-tns-c65-16 ng-trigger ng-trigger-collapseMotion ant-menu ant-menu-inline ant-menu-sub ng-star-inserted&quot;]/ul[@class=&quot;list-sub ng-star-inserted&quot;]/li[@class=&quot;ant-menu-item ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>64cb9b63-9958-462f-95b5-6779a1deac78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6e3ae0f-98e6-404e-a795-85609a1034a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master-data/general</value>
      <webElementGuid>f1991043-9630-4df6-b024-fa37c7f8a8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General </value>
      <webElementGuid>fc431e07-4f10-4b46-b4e0-9f18eef8d1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-open&quot;]/div[@class=&quot;ng-tns-c65-16 ng-trigger ng-trigger-collapseMotion ant-menu ant-menu-inline ant-menu-sub ng-star-inserted&quot;]/ul[@class=&quot;list-sub ng-star-inserted&quot;]/li[@class=&quot;ant-menu-item ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>b202728f-e6f7-4ca9-9920-3fcf0ff551f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a39a3511-f990-4efe-8789-2ecf0741967d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master-data/general</value>
      <webElementGuid>33b0d803-3540-438c-9f89-7996dbcacfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General </value>
      <webElementGuid>6ea5d977-9b28-4428-89dc-727cce2ec38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-open&quot;]/div[@class=&quot;ng-tns-c65-16 ng-trigger ng-trigger-collapseMotion ant-menu ant-menu-inline ant-menu-sub ng-star-inserted&quot;]/ul[@class=&quot;list-sub ng-star-inserted&quot;]/li[@class=&quot;ant-menu-item ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>4bd14649-56ca-422d-8af0-4d192c597274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e23a30c-adf5-42f4-941a-3f74875610af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master-data/general</value>
      <webElementGuid>3900ed7f-8bee-4716-b616-c26d88484a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General </value>
      <webElementGuid>9177247c-9807-46b7-85b1-dad4f9622a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps ps--active-y ps--scrolling-y&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-open&quot;]/div[@class=&quot;ng-tns-c65-16 ng-trigger ng-trigger-collapseMotion ant-menu ant-menu-inline ant-menu-sub ng-star-inserted&quot;]/ul[@class=&quot;list-sub ng-star-inserted&quot;]/li[@class=&quot;ant-menu-item ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>fd2b79db-af71-48c8-a8d3-a35e91a5456c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>192fe72e-6db0-40da-9052-c8259dcb95fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master-data/general</value>
      <webElementGuid>688c1ef8-ce8d-4118-aed1-76ea1edc7bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General </value>
      <webElementGuid>c4f7f5b2-31b6-47d4-90bf-dfbcef526dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-open&quot;]/div[@class=&quot;ng-tns-c65-16 ng-trigger ng-trigger-collapseMotion ant-menu ant-menu-inline ant-menu-sub ng-star-inserted&quot;]/ul[@class=&quot;list-sub ng-star-inserted&quot;]/li[@class=&quot;ant-menu-item ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>e303f8a9-e442-45da-b052-d61f612fee09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[1]/following::a[1]</value>
      <webElementGuid>a29cee80-b768-49b5-8d10-91e3ba0d6fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen User'])[1]/following::a[1]</value>
      <webElementGuid>0841b659-3e25-40a8-94c0-be80e0b370a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment'])[1]/preceding::a[1]</value>
      <webElementGuid>d1d15672-0163-42b5-9071-02d44a3ea85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/master-data/general')]</value>
      <webElementGuid>381e8987-c276-4ea3-a0cc-ff11f9c47d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div[2]/ul/li/a</value>
      <webElementGuid>f5163125-c9e6-4ec1-861d-c3e68f064e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/master-data/general' and (text() = 'General ' or . = 'General ')]</value>
      <webElementGuid>0404ad51-c081-4417-9129-c7c7ec6ead63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
