<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>384b1c44-aa4d-4807-8d9c-999069227c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ng-tns-c172-23.ant-btn.ant-btn-primary.ant-btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-3']/div/div/div[2]/div/div/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13fcd012-65bd-4365-a552-59e009b5f0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c172-23 ant-btn ant-btn-primary ant-btn-sm</value>
      <webElementGuid>1365817e-2a26-4b3c-b7a2-593a2771f01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>13607aee-3e9c-4f05-aa86-4b0ae703f925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-3&quot;)/div[@class=&quot;ant-popover ng-tns-c172-23 ng-trigger ng-trigger-zoomBigMotion ng-star-inserted null ant-popover-placement-left&quot;]/div[@class=&quot;ant-popover-content ng-tns-c172-23&quot;]/div[@class=&quot;ant-popover-inner ng-tns-c172-23&quot;]/div[@class=&quot;ng-tns-c172-23&quot;]/div[@class=&quot;ant-popover-inner-content ng-tns-c172-23&quot;]/div[@class=&quot;ant-popover-buttons ng-tns-c172-23&quot;]/button[@class=&quot;ng-tns-c172-23 ant-btn ant-btn-primary ant-btn-sm&quot;]</value>
      <webElementGuid>70abadad-9503-43dc-97a6-c03b0eb8e9c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/div/div/div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>9d2ed082-3db2-475e-a5c3-e0ccd750a88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>5a9a26f2-a3a5-4e46-8da8-502fdef0b199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda yakin akan menghapus data cabang ini?'])[1]/following::button[2]</value>
      <webElementGuid>a77fab11-f01a-4028-bb3b-7c3f9fd0c75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>ed6ce33f-3f82-4587-832c-436593c87634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>4324849c-215b-45c6-850d-7956e9847a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
