<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Master Data</name>
   <tag></tag>
   <elementGuidId>9bf61d74-e216-4394-bbbb-f4a3bb9a9ee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ant-menu-submenu.ant-menu-submenu-inline.ng-star-inserted.ant-menu-submenu-active > div.ant-menu-submenu-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen User'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49f5ce2b-5700-4528-be1a-fd5ec99c00f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-submenu-title</value>
      <webElementGuid>3579a8a1-b74f-4f50-8725-a0e50e3d0b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data</value>
      <webElementGuid>d68d84f5-316d-416f-ad82-5af389d60782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-active&quot;]/div[@class=&quot;ant-menu-submenu-title&quot;]</value>
      <webElementGuid>d02d08f7-a054-4e45-b783-42c1f568896b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d27a564-e35a-4790-974a-f6bd6c025816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-submenu-title</value>
      <webElementGuid>ed158950-296c-495f-b9bf-8203f212baa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data</value>
      <webElementGuid>085bd4a3-1ede-46ce-bc22-5d3b60ce787e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-active&quot;]/div[@class=&quot;ant-menu-submenu-title&quot;]</value>
      <webElementGuid>ae655657-d80d-4138-84e3-721e0bd8a828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8fe68a4a-fc29-45d8-bb83-16641f27030b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-submenu-title</value>
      <webElementGuid>fcfc53c6-e818-4175-91a1-70a790782f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data</value>
      <webElementGuid>c00b7735-9ae4-4280-96d1-dce119f2dbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-active&quot;]/div[@class=&quot;ant-menu-submenu-title&quot;]</value>
      <webElementGuid>84e2b30e-cfa9-4d51-8449-0dc74e6964d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>321500ac-5bbb-462b-88f6-d55dfa17c005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-submenu-title</value>
      <webElementGuid>e022d116-3c36-4d7e-a6aa-63e87a0bd894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data</value>
      <webElementGuid>0f1d1b5a-1535-424a-aeb9-425437a050a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-active&quot;]/div[@class=&quot;ant-menu-submenu-title&quot;]</value>
      <webElementGuid>0e806354-c04e-40e0-b505-96f34330133e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2b2c8591-0254-4118-b1a1-0796f328b637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-submenu-title</value>
      <webElementGuid>6d3c9b90-e63e-4a23-8077-0a7ca2fffb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data</value>
      <webElementGuid>9635f633-c481-4155-9e1b-33529ddb4fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-active&quot;]/div[@class=&quot;ant-menu-submenu-title&quot;]</value>
      <webElementGuid>f72ba362-fe05-412a-ab94-badf946cfeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3fe40e85-5491-4495-a02f-ff1a34c981ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-submenu-title</value>
      <webElementGuid>81a303b1-17cc-483d-a9db-940964058e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data</value>
      <webElementGuid>093509cb-5e17-4f1a-b077-fe2ecefe1e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-active&quot;]/div[@class=&quot;ant-menu-submenu-title&quot;]</value>
      <webElementGuid>9bca7c9c-7c22-4663-a0da-b9f5ccf31acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d4cfadc7-896d-49cc-a4d9-894952a0f547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-submenu-title</value>
      <webElementGuid>24d81807-f677-46a9-897e-e5ad9e198ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data</value>
      <webElementGuid>22c205e5-3822-4d1f-bef6-89a563139eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ng-star-inserted ant-menu-submenu-active&quot;]/div[@class=&quot;ant-menu-submenu-title&quot;]</value>
      <webElementGuid>9d5c994f-6ea6-41a6-bf79-5e816dabc013</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen User'])[1]/following::div[1]</value>
      <webElementGuid>daaef7f9-1f28-4680-9611-5e83eb68a6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIE Batch Alignment'])[1]/following::div[3]</value>
      <webElementGuid>5ab5f88d-c45e-45c3-9ab0-2caf40832a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/preceding::div[2]</value>
      <webElementGuid>38a18873-3e7a-478c-92d7-ef75bf5f2c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div</value>
      <webElementGuid>a8e2de7e-55b7-4096-9ca2-90f76ca455e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Master Data' or . = 'Master Data')]</value>
      <webElementGuid>85d71916-3095-48ba-ad82-570fc359ab0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
