<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LOGISTIC OPERATION PORTALSilahkan masuk_19d277</name>
   <tag></tag>
   <elementGuidId>932cce04-e01d-44cd-a94f-b113bc7d8bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_login']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kt-login__body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>669044a2-eabc-401e-8e14-ae1121ff39db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt-login__body</value>
      <webElementGuid>481d958c-0862-4114-8825-bef58b403b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGISTIC OPERATION PORTALSilahkan masuk menggunakan akun Anda.Mohon masukkan Username!MASUKLupa Kata Sandi</value>
      <webElementGuid>0ad430de-0471-4160-bdbe-cf97df3a3895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login&quot;)/div[@class=&quot;kt-grid__item kt-grid__item--fluid kt-grid kt-grid--desktop kt-grid--ver-desktop kt-grid--hor-tablet-and-mobile&quot;]/div[@class=&quot;kt-grid__item kt-grid__item--order-tablet-and-mobile-2 kt-login__aside&quot;]/div[@class=&quot;kt-grid__item kt-grid__item--fluid kt-grid__item--order-tablet-and-mobile-1 kt-login__wrapper&quot;]/div[@class=&quot;kt-login__body&quot;]</value>
      <webElementGuid>0984bad0-bbbf-4480-a507-2abc14a63a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_login']/div/div/div/div</value>
      <webElementGuid>e662ba50-39e2-48e3-9454-817bd5ada68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div</value>
      <webElementGuid>db472ba1-f50e-49e4-bf8f-70f35086ad19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LOGISTIC OPERATION PORTALSilahkan masuk menggunakan akun Anda.Mohon masukkan Username!MASUKLupa Kata Sandi' or . = 'LOGISTIC OPERATION PORTALSilahkan masuk menggunakan akun Anda.Mohon masukkan Username!MASUKLupa Kata Sandi')]</value>
      <webElementGuid>3370fc2f-601b-4e07-89a7-e939b390207d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
