<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_MASUKLupa Kata Sandi</name>
   <tag></tag>
   <elementGuidId>687a76e5-2531-4ba4-8c9f-29ccc3cc139e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='app_login_form']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app_login_form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>bddfd091-fcd0-4dd3-bd2b-21fde55b42b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_login_form</value>
      <webElementGuid>aca4ffba-54bf-4bcb-88f2-f5740431a290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt-form ant-form ant-form-horizontal ng-dirty ng-touched ng-valid</value>
      <webElementGuid>559cea7d-65d7-4583-9ba0-607aacfdbc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MASUKLupa Kata Sandi</value>
      <webElementGuid>9dc7855b-2e2e-449d-a364-a255cf5d9933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_login_form&quot;)</value>
      <webElementGuid>69a9ddb1-ecec-48cb-8c97-f45acc8ebbcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='app_login_form']</value>
      <webElementGuid>bd9e2aef-9707-4c80-a798-018c36cd77a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_login']/div/div/div/div/div/nz-spin/div/form</value>
      <webElementGuid>cd806d46-d314-4456-994e-bcd1f4c9066c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGISTIC OPERATION PORTAL'])[1]/following::form[1]</value>
      <webElementGuid>bcb9866f-a18c-41c8-83ae-c81867270591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>46ff4ffd-ff7e-49d6-9229-3125f7d4430b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'app_login_form' and (text() = 'MASUKLupa Kata Sandi' or . = 'MASUKLupa Kata Sandi')]</value>
      <webElementGuid>eb74d60f-1edd-465b-a80a-674cc7dc60b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
