<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Cabang_ant-input ng-tns-c126-44 _a242a7</name>
   <tag></tag>
   <elementGuidId>46dcf025-af5b-4c34-84e2-aa89869823b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.ng-tns-c126-44.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-2']/nz-modal-container/div/div/div[2]/form/div/div[2]/nz-form-item/nz-form-control/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7dc7064c-efef-4c4f-b1b3-628fc149744d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>plant</value>
      <webElementGuid>dac1a057-5948-49ae-9de7-59c88885cf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Cabang</value>
      <webElementGuid>1b0312ad-df58-4eb1-83bb-8404c987c2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ng-tns-c126-44 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cde35f95-6d9a-4f28-a96e-f1064a102061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-2&quot;)/nz-modal-container[@class=&quot;ng-tns-c150-42 ng-trigger ng-trigger-modalContainer ant-modal-wrap ng-star-inserted&quot;]/div[@class=&quot;ant-modal ng-tns-c150-42&quot;]/div[@class=&quot;ant-modal-content ng-tns-c150-42&quot;]/div[@class=&quot;ant-modal-body ng-tns-c150-42&quot;]/form[@class=&quot;ant-form ng-valid ant-form-vertical ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/nz-form-item[@class=&quot;ant-form-item ant-row&quot;]/nz-form-control[@class=&quot;ng-tns-c126-44 ant-form-item-control ant-col ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c126-44&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c126-44&quot;]/input[@class=&quot;ant-input ng-tns-c126-44 ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>44965f55-6fc3-4e95-8758-adba63be6e27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/nz-modal-container/div/div/div[2]/form/div/div[2]/nz-form-item/nz-form-control/div/div/input</value>
      <webElementGuid>1cbee2fb-a542-4cfd-9436-34309126ce77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nz-form-item/nz-form-control/div/div/input</value>
      <webElementGuid>60667732-ba93-46e2-af48-64bf1053c554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan Nama Cabang']</value>
      <webElementGuid>9d5da185-d5cc-447e-b290-53f8a057a2e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
